resources:
#- certificates/dev-mq-client-certificate.yaml
#- certificates/dev-mq-server-certificate.yaml

## NOTES:
## - mq-infra/* is expliclity not handled here as it is handled by 
##    /mq/config/argocd/dev/dev-mq-infra-instance.yaml
## - mq-spring-app/* is expliclity not handled here as it is handled by 
##    /mq/config/argocd/dev/dev-mq-spring-app-instance.yaml
